export const products = [
  {
    id: "TRC101",
    name: "All-Purpose 2WD Tractor",
    description:
      "A versatile 2-wheel-drive tractor ideal for general farming activities.",
    category: "Tractors",
    tags: ["2WD", "versatile", "farming"],
    price: 45000,
    discountPrice: 42500,
    discountPercentage: 5,
    unit: "per unit",
    stock: 20,
    images: [
      "products/all-purpose-2wd-tractor-1.jpg",
      "products/all-purpose-2wd-tractor-2.jpg",
    ],
    details: {
      engine_power: "120 HP",
      transmission: "6-speed manual",
      fuel_capacity: "80 liters",
      max_speed: "35 km/h",
    },
  },
  {
    id: "TRC102",
    name: "Compact Utility Tractor",
    description: "A compact tractor perfect for small to medium-sized farms.",
    category: "Tractors",
    tags: ["compact", "utility", "farm"],
    price: 42000,
    unit: "per unit",
    stock: 10,
    images: ["products/compact-utility-tractor-1.jpg"],
    details: {
      engine_power: "100 HP",
      transmission: "5-speed manual",
      fuel_capacity: "70 liters",
      max_speed: "30 km/h",
    },
  },
  {
    id: "TRC103",
    name: "High-Torque 4WD Tractor",
    description: "A powerful 4-wheel-drive tractor built for heavy-duty tasks.",
    category: "Tractors",
    tags: ["4WD", "high-torque", "heavy-duty"],
    price: 58000,
    discountPrice: 55000,
    discountPercentage: 5,
    unit: "per unit",
    stock: 8,
    images: ["products/high-torque-4wd-tractor-1.jpg"],
    details: {
      engine_power: "180 HP",
      transmission: "10-speed manual",
      fuel_capacity: "120 liters",
      max_speed: "45 km/h",
    },
  },
  {
    id: "TRC104",
    name: "Standard 2WD Tractor",
    description:
      "A reliable 2-wheel-drive tractor suitable for everyday farm work.",
    category: "Tractors",
    tags: ["2WD", "standard", "reliable"],
    price: 43000,
    unit: "per unit",
    stock: 12,
    images: [
      "products/standard-2wd-tractor-1.jpg",
      "products/standard-2wd-tractor-2.jpg",
    ],
    details: {
      engine_power: "110 HP",
      transmission: "6-speed manual",
      fuel_capacity: "75 liters",
      max_speed: "33 km/h",
    },
  },
  {
    id: "TRC105",
    name: "Heavy-Duty 4WD Tractor",
    description:
      "A robust 4-wheel-drive tractor designed for heavy agricultural tasks and rugged terrains.",
    category: "Tractors",
    tags: ["4WD", "heavy-duty", "agriculture"],
    price: 55000,
    discountPrice: 52000,
    discountPercentage: 5,
    unit: "per unit",
    stock: 15,
    images: [
      "products/heavy-duty-4wd-tractor-1.webp",
      "products/heavy-duty-4wd-tractor-2.webp",
    ],
    details: {
      engine_power: "150 HP",
      transmission: "8-speed manual",
      fuel_capacity: "100 liters",
      max_speed: "40 km/h",
    },
  },
  {
    id: "TRC106",
    name: "Advanced 4WD Tractor",
    description:
      "An advanced 4-wheel-drive tractor with enhanced features for modern farms.",
    category: "Tractors",
    tags: ["4WD", "advanced", "modern"],
    price: 59000,
    discountPrice: 57000,
    discountPercentage: 3,
    unit: "per unit",
    stock: 7,
    images: [
      "products/advanced-4wd-tractor-1.jpg",
      "products/advanced-4wd-tractor-2.jpg",
    ],
    details: {
      engine_power: "200 HP",
      transmission: "12-speed manual",
      fuel_capacity: "150 liters",
      max_speed: "50 km/h",
    },
  },
  {
    id: "TRC107",
    name: "Utility 2WD Tractor",
    description:
      "A reliable 2-wheel-drive tractor for utility and maintenance work.",
    category: "Tractors",
    tags: ["2WD", "utility", "maintenance"],
    price: 41000,
    unit: "per unit",
    stock: 18,
    images: ["products/utility-2wd-tractor-1.jpg"],
    details: {
      engine_power: "95 HP",
      transmission: "5-speed manual",
      fuel_capacity: "60 liters",
      max_speed: "28 km/h",
    },
  },
  {
    id: "TRC108",
    name: "Economy 2WD Tractor",
    description:
      "An economical 2-wheel-drive tractor suitable for budget-conscious buyers.",
    category: "Tractors",
    tags: ["2WD", "economy", "budget"],
    price: 40000,
    unit: "per unit",
    stock: 25,
    images: ["products/economy-2wd-tractor-1.jpg"],
    details: {
      engine_power: "85 HP",
      transmission: "4-speed manual",
      fuel_capacity: "50 liters",
      max_speed: "25 km/h",
    },
  },
  {
    id: "TRC109",
    name: "Powerful 4WD Tractor",
    description:
      "A high-powered 4-wheel-drive tractor designed for large-scale operations.",
    category: "Tractors",
    tags: ["4WD", "powerful", "large-scale"],
    price: 56000,
    discountPrice: 54000,
    discountPercentage: 4,
    unit: "per unit",
    stock: 6,
    images: [
      "products/powerful-4wd-tractor-1.jpg",
      "products/powerful-4wd-tractor-2.jpg",
    ],
    details: {
      engine_power: "160 HP",
      transmission: "9-speed manual",
      fuel_capacity: "110 liters",
      max_speed: "42 km/h",
    },
  },
  {
    id: "TRC110",
    name: "Precision 4WD Tractor",
    description:
      "A 4-wheel-drive tractor with precise control features for specialized tasks.",
    category: "Tractors",
    tags: ["4WD", "precision", "specialized"],
    price: 57000,
    discountPrice: 55000,
    discountPercentage: 3,
    unit: "per unit",
    stock: 5,
    images: [
      "products/precision-4wd-tractor-1.jpg",
      "products/precision-4wd-tractor-2.jpg",
    ],
    details: {
      engine_power: "170 HP",
      transmission: "11-speed manual",
      fuel_capacity: "130 liters",
      max_speed: "48 km/h",
    },
  },
  // //////////////////////////////// rebase ////////////////////////////// //
  {
    id: "TRC002",
    name: "Agricultural Sprayer Tractor",
    description:
      "A versatile tractor equipped with a sprayer, ideal for efficiently irrigating and protecting crops.",
    category: "Tractors",
    tags: ["sprayer", "agriculture", "irrigation"],
    price: 45000,
    discountPrice: 42500,
    discountPercentage: 5,
    unit: "per unit",
    stock: 10,
    images: [
      "products/agricultural-sprayer-tractor-1.jpg",
      "products/agricultural-sprayer-tractor-2.jpg",
      "products/agricultural-sprayer-tractor-3.jpg",
    ],
    details: {
      engine_power: "100 HP",
      transmission: "6-speed automatic",
      fuel_capacity: "120 liters",
      max_speed: "35 km/h",
    },
  },
  {
    id: "TRC001",
    name: "Heavy-Duty 4WD Tractor",
    description:
      "A robust 4-wheel-drive tractor designed for heavy agricultural tasks and rugged terrains.",
    category: "Tractors",
    tags: ["4WD", "heavy-duty", "agriculture"],
    price: 55000,
    discountPrice: 52000,
    discountPercentage: 5,
    unit: "per unit",
    stock: 15,
    images: [
      "products/heavy-duty-4wd-tractor-3.jpg",
      "products/heavy-duty-4wd-tractor-1.jpg",
      "products/heavy-duty-4wd-tractor-2.jpg",
    ],
    details: {
      engine_power: "150 HP",
      transmission: "8-speed manual",
      fuel_capacity: "100 liters",
      max_speed: "40 km/h",
    },
  },
  {
    id: "AGR001",
    name: "High-Yield Corn Seeds",
    description:
      "Genetically optimized corn seeds for maximum yield and drought resistance.",
    category: "Seeds",
    tags: ["corn", "high-yield", "drought-resistant"],
    price: 1200,
    discountPrice: 1080,
    discountPercentage: 10,
    unit: "per 25kg bag",
    stock: 500,
    images: ["products/corn-seeds-1.jpg", "products/corn-seeds-2.jpg"],
    details: {
      germination_rate: "95%",
      growth_period: "90-120 days",
      recommended_soil_ph: "5.8-7.0",
    },
  },
  {
    id: "AGR008",
    name: "Compact Tractor",
    description:
      "Versatile 40HP compact tractor suitable for small to medium-sized farms.",
    category: "Machinery",
    tags: ["tractor", "farm-equipment", "compact"],
    price: 35000,
    unit: "per tractor",
    stock: 20,
    images: [
      "products/compact-tractor-1.jpg",
      "products/compact-tractor-2.jpg",
    ],
    details: {
      horsepower: "40 HP",
      fuel_type: "Diesel",
      transmission: "8 forward, 8 reverse gears",
    },
  },
  {
    id: "AGR002",
    name: "Precision Farming Drone",
    description:
      "Advanced drone with multispectral imaging for crop health monitoring and precision agriculture.",
    category: "Technology",
    tags: ["drone", "precision-farming", "crop-monitoring"],
    price: 15000,
    unit: "per unit",
    stock: 50,
    images: ["products/farming-drone-1.jpg", "products/farming-drone-2.jpg"],
    details: {
      flight_time: "45 minutes",
      camera_resolution: "20MP",
      maximum_coverage: "60 hectares per flight",
    },
  },
  {
    id: "AGR003",
    name: "Organic Fertilizer",
    description:
      "100% organic fertilizer made from composted plant materials and animal waste.",
    category: "Fertilizers",
    tags: ["organic", "fertilizer", "eco-friendly"],
    price: 2500,
    discountPrice: 2250,
    discountPercentage: 10,
    unit: "per ton",
    stock: 1000,
    images: [
      "products/organic-fertilizer-1.jpg",
      "products/organic-fertilizer-2.jpg",
    ],
    details: {
      npk_ratio: "4-4-4",
      organic_matter: "65%",
      application_rate: "2-4 tons per hectare",
    },
  },
  {
    id: "AGR004",
    name: "Smart Irrigation System",
    description:
      "IoT-based irrigation system with soil moisture sensors and weather integration.",
    category: "Irrigation",
    tags: ["smart-irrigation", "water-saving", "iot"],
    price: 8000,
    unit: "per system (covers 10 hectares)",
    stock: 100,
    images: [
      "products/smart-irrigation-1.jpg",
      "products/smart-irrigation-2.jpg",
    ],
    details: {
      water_saving: "Up to 30%",
      sensor_types: "Soil moisture, temperature, humidity",
      control: "Smartphone app and web interface",
    },
  },
  {
    id: "AGR005",
    name: "Vertical Farming Kit",
    description:
      "Complete vertical farming system for urban agriculture, includes grow lights and hydroponic setup.",
    category: "Urban Farming",
    tags: ["vertical-farming", "hydroponics", "urban-agriculture"],
    price: 12000,
    discountPrice: 10800,
    discountPercentage: 10,
    unit: "per kit",
    stock: 30,
    images: [
      "products/vertical-farming-1.jpg",
      "products/vertical-farming-2.jpg",
    ],
    details: {
      growing_area: "10 square meters",
      plant_capacity: "Up to 200 plants",
      power_consumption: "1.5 kW/day",
    },
  },
  {
    id: "AGR006",
    name: "Livestock Monitoring Collars",
    description:
      "GPS-enabled collars for tracking and monitoring the health of livestock.",
    category: "Livestock Management",
    tags: ["gps-tracking", "livestock-health", "farm-management"],
    price: 5000,
    unit: "per set of 10 collars",
    stock: 200,
    images: [
      "products/livestock-collars-1.jpg",
      "products/livestock-collars-2.jpg",
      "products/livestock-collars-3.jpg",
    ],
    details: {
      battery_life: "Up to 5 years",
      tracking_range: "Up to 5 km",
      data_monitored: "Location, temperature, activity levels",
    },
  },
  {
    id: "AGR007",
    name: "Greenhouse Construction Kit",
    description:
      "DIY greenhouse kit with polycarbonate panels and aluminum frame.",
    category: "Structures",
    tags: ["greenhouse", "diy", "crop-protection"],
    price: 7500,
    discountPrice: 6750,
    discountPercentage: 10,
    unit: "per kit (100 sq meters)",
    stock: 50,
    images: ["products/greenhouse-kit-1.jpg", "products/greenhouse-kit-2.jpg"],
    details: {
      size: "10m x 10m x 3m (LxWxH)",
      material: "4mm twin-wall polycarbonate, aluminum frame",
      includes: "Ventilation system, assembly tools",
    },
  },

  {
    id: "AGR009",
    name: "Beekeeping Starter Kit",
    description:
      "Complete kit for starting a beekeeping operation, includes hive, protective gear, and tools.",
    category: "Beekeeping",
    tags: ["bees", "honey-production", "pollination"],
    price: 1500,
    unit: "per kit",
    stock: 100,
    images: ["products/beekeeping-kit-1.jpg", "products/beekeeping-kit-2.jpg"],
    details: {
      hive_type: "Langstroth",
      includes: "Hive, frames, smoker, hive tool, protective suit",
      suitable_for: "Up to 50,000 bees",
    },
  },
];
