export const products = [
  {
    id: "TRC001",
    name: "Heavy-Duty 4WD Tractor",
    description:
      "A robust 4-wheel-drive tractor designed for heavy agricultural tasks and rugged terrains.",
    category: "Tractors",
    tags: ["4WD", "heavy-duty", "agriculture"],
    price: 55000,
    discountPrice: 52000,
    discountPercentage: 5,
    unit: "per unit",
    stock: 15,
    images: [
      "products/heavy-duty-4wd-tractor-3.jpg",
      "products/heavy-duty-4wd-tractor-1.jpg",
      "products/heavy-duty-4wd-tractor-2.jpg",
    ],
    details: {
      engine_power: "150 HP",
      transmission: "8-speed manual",
      fuel_capacity: "100 liters",
      max_speed: "40 km/h",
    },
  },
  {
    id: "AGR001",
    name: "High-Yield Corn Seeds",
    description:
      "Genetically optimized corn seeds for maximum yield and drought resistance.",
    category: "Seeds",
    tags: ["corn", "high-yield", "drought-resistant"],
    price: 1200,
    discountPrice: 1080,
    discountPercentage: 10,
    unit: "per 25kg bag",
    stock: 500,
    images: ["products/corn-seeds-1.jpg", "products/corn-seeds-2.jpg"],
    details: {
      germination_rate: "95%",
      growth_period: "90-120 days",
      recommended_soil_ph: "5.8-7.0",
    },
  },
  {
    id: "AGR002",
    name: "Precision Farming Drone",
    description:
      "Advanced drone with multispectral imaging for crop health monitoring and precision agriculture.",
    category: "Technology",
    tags: ["drone", "precision-farming", "crop-monitoring"],
    price: 15000,
    unit: "per unit",
    stock: 50,
    images: ["products/farming-drone-1.jpg", "products/farming-drone-2.jpg"],
    details: {
      flight_time: "45 minutes",
      camera_resolution: "20MP",
      maximum_coverage: "60 hectares per flight",
    },
  },
  {
    id: "AGR003",
    name: "Organic Fertilizer",
    description:
      "100% organic fertilizer made from composted plant materials and animal waste.",
    category: "Fertilizers",
    tags: ["organic", "fertilizer", "eco-friendly"],
    price: 2500,
    discountPrice: 2250,
    discountPercentage: 10,
    unit: "per ton",
    stock: 1000,
    images: [
      "products/organic-fertilizer-1.jpg",
      "products/organic-fertilizer-2.jpg",
    ],
    details: {
      npk_ratio: "4-4-4",
      organic_matter: "65%",
      application_rate: "2-4 tons per hectare",
    },
  },
  {
    id: "AGR004",
    name: "Smart Irrigation System",
    description:
      "IoT-based irrigation system with soil moisture sensors and weather integration.",
    category: "Irrigation",
    tags: ["smart-irrigation", "water-saving", "iot"],
    price: 8000,
    unit: "per system (covers 10 hectares)",
    stock: 100,
    images: [
      "products/smart-irrigation-1.jpg",
      "products/smart-irrigation-2.jpg",
    ],
    details: {
      water_saving: "Up to 30%",
      sensor_types: "Soil moisture, temperature, humidity",
      control: "Smartphone app and web interface",
    },
  },
  {
    id: "AGR005",
    name: "Vertical Farming Kit",
    description:
      "Complete vertical farming system for urban agriculture, includes grow lights and hydroponic setup.",
    category: "Urban Farming",
    tags: ["vertical-farming", "hydroponics", "urban-agriculture"],
    price: 12000,
    discountPrice: 10800,
    discountPercentage: 10,
    unit: "per kit",
    stock: 30,
    images: [
      "products/vertical-farming-1.jpg",
      "products/vertical-farming-2.jpg",
    ],
    details: {
      growing_area: "10 square meters",
      plant_capacity: "Up to 200 plants",
      power_consumption: "1.5 kW/day",
    },
  },
  {
    id: "AGR006",
    name: "Livestock Monitoring Collars",
    description:
      "GPS-enabled collars for tracking and monitoring the health of livestock.",
    category: "Livestock Management",
    tags: ["gps-tracking", "livestock-health", "farm-management"],
    price: 5000,
    unit: "per set of 10 collars",
    stock: 200,
    images: [
      "products/livestock-collars-1.jpg",
      "products/livestock-collars-2.jpg",
    ],
    details: {
      battery_life: "Up to 5 years",
      tracking_range: "Up to 5 km",
      data_monitored: "Location, temperature, activity levels",
    },
  },
  {
    id: "AGR007",
    name: "Greenhouse Construction Kit",
    description:
      "DIY greenhouse kit with polycarbonate panels and aluminum frame.",
    category: "Structures",
    tags: ["greenhouse", "diy", "crop-protection"],
    price: 7500,
    discountPrice: 6750,
    discountPercentage: 10,
    unit: "per kit (100 sq meters)",
    stock: 50,
    images: ["products/greenhouse-kit-1.jpg", "products/greenhouse-kit-2.jpg"],
    details: {
      size: "10m x 10m x 3m (LxWxH)",
      material: "4mm twin-wall polycarbonate, aluminum frame",
      includes: "Ventilation system, assembly tools",
    },
  },
  {
    id: "AGR008",
    name: "Compact Tractor",
    description:
      "Versatile 40HP compact tractor suitable for small to medium-sized farms.",
    category: "Machinery",
    tags: ["tractor", "farm-equipment", "compact"],
    price: 35000,
    unit: "per tractor",
    stock: 20,
    images: [
      "products/compact-tractor-1.jpg",
      "products/compact-tractor-2.jpg",
    ],
    details: {
      horsepower: "40 HP",
      fuel_type: "Diesel",
      transmission: "8 forward, 8 reverse gears",
    },
  },
  {
    id: "AGR009",
    name: "Beekeeping Starter Kit",
    description:
      "Complete kit for starting a beekeeping operation, includes hive, protective gear, and tools.",
    category: "Beekeeping",
    tags: ["bees", "honey-production", "pollination"],
    price: 1500,
    unit: "per kit",
    stock: 100,
    images: ["products/beekeeping-kit-1.jpg", "products/beekeeping-kit-2.jpg"],
    details: {
      hive_type: "Langstroth",
      includes: "Hive, frames, smoker, hive tool, protective suit",
      suitable_for: "Up to 50,000 bees",
    },
  },
  {
    id: "AGR010",
    name: "Hydroponic Nutrient Solution",
    description:
      "Balanced nutrient solution for hydroponic and soilless growing systems.",
    category: "Fertilizers",
    tags: ["hydroponics", "nutrients", "soilless-growing"],
    price: 1200,
    unit: "per 200L drum",
    stock: 500,
    images: [
      "products/hydroponic-nutrients-1.jpg",
      "products/hydroponic-nutrients-2.jpg",
    ],
    details: {
      npk_ratio: "3-2-6",
      ph_balanced: "Yes",
      suitable_for: "All growth stages",
    },
  },
  {
    id: "AGR011",
    name: "Solar Water Pump System",
    description:
      "Off-grid solar-powered water pump system for irrigation and livestock.",
    category: "Irrigation",
    tags: ["solar-power", "water-pump", "off-grid"],
    price: 6000,
    discountPrice: 5400,
    discountPercentage: 10,
    unit: "per system",
    stock: 75,
    images: ["products/solar-pump-1.jpg", "products/solar-pump-2.jpg"],
    details: {
      solar_panel_capacity: "1000W",
      max_flow_rate: "5000L/hour",
      max_head: "50 meters",
    },
  },
  {
    id: "AGR012",
    name: "Precision Seeder",
    description:
      "High-accuracy seeder for uniform plant spacing and depth control.",
    category: "Machinery",
    tags: ["seeding", "precision-agriculture", "row-crops"],
    price: 25000,
    unit: "per unit",
    stock: 30,
    images: [
      "products/precision-seeder-1.jpg",
      "products/precision-seeder-2.jpg",
    ],
    details: {
      row_capacity: "6 rows",
      seed_types: "Compatible with most grain and vegetable seeds",
      working_width: "3 meters",
    },
  },
  {
    id: "AGR013",
    name: "Organic Pest Control Kit",
    description:
      "Set of organic pesticides and beneficial insects for natural pest management.",
    category: "Pest Control",
    tags: ["organic", "pest-management", "beneficial-insects"],
    price: 2000,
    unit: "per kit (treats 1 hectare)",
    stock: 150,
    images: [
      "products/organic-pest-control-1.jpg",
      "products/organic-pest-control-2.jpg",
    ],
    details: {
      includes: "Neem oil, pyrethrin, predatory mites, lacewings",
      application_method: "Spray and release",
      safety: "Safe for humans and beneficial insects",
    },
  },
  {
    id: "AGR014",
    name: "Mushroom Growing Kit",
    description:
      "Complete kit for growing gourmet mushrooms, includes spores and growing medium.",
    category: "Specialty Crops",
    tags: ["mushrooms", "gourmet-crops", "indoor-farming"],
    price: 1800,
    discountPrice: 1620,
    discountPercentage: 10,
    unit: "per kit",
    stock: 200,
    images: ["products/mushroom-kit-1.jpg", "products/mushroom-kit-2.jpg"],
    details: {
      mushroom_varieties: "Shiitake, Oyster, Lion's Mane",
      yield: "Up to 5kg per month",
      growing_area_required: "2 square meters",
    },
  },
  {
    id: "AGR015",
    name: "Soil Health Testing Kit",
    description:
      "Professional-grade soil testing kit for nutrient levels, pH, and microbial activity.",
    category: "Soil Management",
    tags: ["soil-testing", "nutrient-management", "precision-agriculture"],
    price: 3500,
    unit: "per kit",
    stock: 100,
    images: [
      "products/soil-testing-kit-1.jpg",
      "products/soil-testing-kit-2.jpg",
    ],
    details: {
      tests_included: "NPK, pH, organic matter, micronutrients",
      test_capacity: "100 samples",
      results_time: "15 minutes per test",
    },
  },
  {
    id: "AGR016",
    name: "Aquaponics System",
    description:
      "Integrated aquaponics system for fish and vegetable production.",
    category: "Aquaculture",
    tags: ["aquaponics", "sustainable-farming", "fish-and-vegetables"],
    price: 9500,
    unit: "per system",
    stock: 40,
    images: [
      "products/aquaponics-system-1.jpg",
      "products/aquaponics-system-2.jpg",
    ],
    details: {
      fish_tank_capacity: "1000L",
      growing_bed_area: "4 square meters",
      recommended_fish: "Tilapia, trout, or catfish",
    },
  },
  {
    id: "AGR017",
    name: "Weather Station",
    description:
      "Professional weather station for accurate local weather monitoring and forecasting.",
    category: "Technology",
    tags: ["weather-monitoring", "precision-agriculture", "data-collection"],
    price: 4500,
    discountPrice: 4050,
    discountPercentage: 10,
    unit: "per station",
    stock: 80,
    images: [
      "products/weather-station-1.jpg",
      "products/weather-station-2.jpg",
    ],
    details: {
      measurements:
        "Temperature, humidity, rainfall, wind speed/direction, solar radiation",
      data_logging: "Yes, with cloud integration",
      power_source: "Solar with battery backup",
    },
  },
  {
    id: "AGR018",
    name: "Fruit Tree Grafting Kit",
    description:
      "Comprehensive kit for grafting fruit trees, includes tools and grafting tape.",
    category: "Horticulture",
    tags: ["grafting", "fruit-trees", "plant-propagation"],
    price: 1500,
    unit: "per kit",
    stock: 150,
    images: ["products/grafting-kit-1.jpg", "products/grafting-kit-2.jpg"],
    details: {
      includes: "Grafting knife, pruning shears, grafting tape, healing balm",
      suitable_for: "Most fruit tree varieties",
      instruction_manual: "Included, with video tutorials",
    },
  },
  {
    id: "AGR019",
    name: "Livestock Feed Mixer",
    description:
      "Large-capacity feed mixer for preparing customized livestock feed blends.",
    category: "Livestock Management",
    tags: ["feed-mixer", "livestock-nutrition", "farm-equipment"],
    price: 18000,
    unit: "per mixer",
    stock: 25,
    images: ["products/feed-mixer-1.jpg", "products/feed-mixer-2.jpg"],
    details: {
      capacity: "2000 kg",
      mixing_time: "5-10 minutes per batch",
      power_source: "PTO or electric motor",
    },
  },
  {
    id: "AGR020",
    name: "Crop Monitoring Sensors",
    description:
      "Wireless sensors for real-time monitoring of crop health, soil moisture, and environmental conditions.",
    category: "Technology",
    tags: ["crop-monitoring", "iot", "precision-agriculture"],
    price: 5000,
    discountPrice: 4500,
    discountPercentage: 10,
    unit: "per set of 10 sensors",
    stock: 100,
    images: ["products/crop-sensors-1.jpg", "products/crop-sensors-2.jpg"],
    details: {
      measurements: "Soil moisture, temperature, light intensity, leaf wetness",
      battery_life: "Up to 2 years",
      data_transmission: "LoRaWAN or cellular",
    },
  },
  {
    id: "AGR021",
    name: "Portable Soil Compaction Tester",
    description:
      "Handheld device for measuring soil compaction levels in fields.",
    category: "Soil Management",
    tags: ["soil-health", "compaction-testing", "field-equipment"],
    price: 2200,
    unit: "per unit",
    stock: 75,
    images: [
      "products/compaction-tester-1.jpg",
      "products/compaction-tester-2.jpg",
    ],
    details: {
      measurement_depth: "Up to 60 cm",
      display: "Digital LCD",
      includes: "Data logging software",
    },
  },
  {
    id: "AGR022",
    name: "Olive Harvester",
    description:
      "Electric olive harvester for efficient and gentle olive collection.",
    category: "Machinery",
    tags: ["olive-harvesting", "fruit-collection", "efficiency"],
    price: 3500,
    unit: "per harvester",
    stock: 50,
    images: [
      "products/olive-harvester-1.jpg",
      "products/olive-harvester-2.jpg",
    ],
    details: {
      harvesting_speed: "Up to 100 kg per hour",
      power_source: "Rechargeable lithium battery",
      weight: "2.5 kg",
    },
  },
  {
    id: "AGR023",
    name: "Vermicomposting Kit",
    description:
      "Complete setup for starting a vermicomposting operation for organic waste recycling.",
    category: "Waste Management",
    tags: ["vermicompost", "organic-fertilizer", "waste-recycling"],
    price: 1800,
    discountPrice: 1620,
    discountPercentage: 10,
    unit: "per kit",
    stock: 100,
    images: [
      "products/vermicompost-kit-1.jpg",
      "products/vermicompost-kit-2.jpg",
    ],
    details: {
      worm_species: "Eisenia fetida (Red Wigglers)",
      bin_capacity: "100 liters",
      includes: "Worm bin, bedding material, 1000 worms",
    },
  },
  {
    id: "AGR024",
    name: "Pollination Beehive Rental",
    description:
      "Rental service for beehives to improve crop pollination during flowering seasons.",
    category: "Pollination Services",
    tags: ["beehives", "crop-pollination", "yield-improvement"],
    price: 2500,
    unit: "per hive per season",
    stock: 200,
    images: ["products/beehive-rental-1.jpg", "products/beehive-rental-2.jpg"],
    details: {
      hive_strength: "Minimum 8 frames of bees",
      rental_period: "4-6 weeks",
      includes: "Hive placement and management",
    },
  },
  {
    id: "AGR025",
    name: "Precision Livestock Scale",
    description:
      "High-accuracy scale for weighing livestock with data logging capabilities.",
    category: "Livestock Management",
    tags: ["livestock-weighing", "data-management", "animal-health"],
    price: 4500,
    unit: "per scale",
    stock: 40,
    images: [
      "products/livestock-scale-1.jpg",
      "products/livestock-scale-2.jpg",
    ],
    details: {
      capacity: "Up to 2000 kg",
      accuracy: "±0.5 kg",
      platform_size: "2m x 1m",
    },
  },
  {
    id: "AGR026",
    name: "Farm Management Software",
    description:
      "Comprehensive software for farm operations management, including crop planning, inventory, and financial tracking.",
    category: "Technology",
    tags: ["farm-management", "software", "data-analysis"],
    price: 1200,
    unit: "per year subscription",
    stock: 500,
    images: ["products/farm-software-1.jpg", "products/farm-software-2.jpg"],
    details: {
      modules: "Crop planning, inventory, financial, reporting",
      platforms: "Web, iOS, and Android",
      support: "24/7 customer support included",
    },
  },
  {
    id: "AGR027",
    name: "Portable Ethylene Ripening System",
    description:
      "Mobile ethylene generator for controlled ripening of fruits post-harvest.",
    category: "Post-Harvest Technology",
    tags: ["fruit-ripening", "post-harvest", "quality-control"],
    price: 7500,
    discountPrice: 6750,
    discountPercentage: 10,
    unit: "per system",
    stock: 30,
    images: [
      "products/ethylene-system-1.jpg",
      "products/ethylene-system-2.jpg",
    ],
    details: {
      capacity: "Suitable for up to 20 cubic meters",
      ethylene_output: "0-100 ppm",
      control: "Automated with safety features",
    },
  },
  {
    id: "AGR028",
    name: "Biochar Production Kiln",
    description:
      "Small-scale biochar production kiln for creating soil amendments and carbon sequestration.",
    category: "Soil Management",
    tags: ["biochar", "soil-amendment", "carbon-sequestration"],
    price: 8500,
    unit: "per kiln",
    stock: 25,
    images: ["products/biochar-kiln-1.jpg", "products/biochar-kiln-2.jpg"],
    details: {
      capacity: "100 kg input per batch",
      production_time: "4-6 hours per batch",
      feedstock: "Agricultural waste, wood chips",
    },
  },
  {
    id: "AGR029",
    name: "Automated Milking System",
    description:
      "Robotic milking system for dairy farms, allowing cows to be milked on their own schedule.",
    category: "Dairy Farming",
    tags: ["automated-milking", "dairy-technology", "animal-welfare"],
    price: 150000,
    unit: "per system",
    stock: 10,
    images: ["products/milking-robot-1.jpg", "products/milking-robot-2.jpg"],
    details: {
      capacity: "Up to 60 cows per robot",
      milk_monitoring: "Individual cow production and health data",
      cleaning: "Automated sanitization after each milking",
    },
  },
  {
    id: "AGR030",
    name: "Solar Electric Fence System",
    description:
      "Solar-powered electric fence system for livestock management and predator control.",
    category: "Livestock Management",
    tags: ["electric-fence", "solar-powered", "livestock-protection"],
    price: 1500,
    unit: "per kit (covers 5000 meters)",
    stock: 100,
    images: ["products/solar-fence-1.jpg", "products/solar-fence-2.jpg"],
    details: {
      power_output: "2 joules",
      solar_panel: "20W with battery backup",
      includes: "Energizer, solar panel, wire, posts, insulators",
    },
  },
  {
    id: "AGR031",
    name: "Portable Fruit Grading Machine",
    description:
      "Mobile fruit sorting and grading machine for various fruit types and sizes.",
    category: "Post-Harvest Technology",
    tags: ["fruit-grading", "quality-control", "efficiency"],
    price: 12000,
    discountPrice: 10800,
    discountPercentage: 10,
    unit: "per machine",
    stock: 20,
    images: ["products/fruit-grader-1.jpg", "products/fruit-grader-2.jpg"],
    details: {
      capacity: "2 tons per hour",
      grading_criteria: "Size, color, weight",
      fruit_types: "Apples, oranges, peaches, etc.",
    },
  },
  {
    id: "AGR032",
    name: "Microgreens Growing System",
    description:
      "Complete system for year-round microgreens production, including trays, lights, and irrigation.",
    category: "Urban Farming",
    tags: ["microgreens", "indoor-farming", "year-round-production"],
    price: 3500,
    unit: "per system",
    stock: 50,
    images: [
      "products/microgreens-system-1.jpg",
      "products/microgreens-system-2.jpg",
    ],
    details: {
      growing_area: "2 square meters",
      production_capacity: "10-15 kg per week",
      includes: "LED grow lights, irrigation system, 50 growing trays",
    },
  },
  {
    id: "AGR033",
    name: "Tractor-Mounted Sprayer",
    description:
      "High-capacity sprayer for efficient application of pesticides and liquid fertilizers.",
    category: "Machinery",
    tags: ["sprayer", "pest-control", "fertilizer-application"],
    price: 22000,
    unit: "per sprayer",
    stock: 15,
    images: [
      "products/tractor-sprayer-1.jpg",
      "products/tractor-sprayer-2.jpg",
    ],
    details: {
      tank_capacity: "1000 liters",
      boom_width: "12 meters",
      nozzle_spacing: "50 cm",
    },
  },
  {
    id: "AGR034",
    name: "Hydroponic Fodder System",
    description:
      "Automated system for producing fresh fodder for livestock using hydroponic technology.",
    category: "Livestock Management",
    tags: ["hydroponics", "fodder-production", "livestock-feed"],
    price: 9500,
    unit: "per system",
    stock: 30,
    images: ["products/fodder-system-1.jpg", "products/fodder-system-2.jpg"],
    details: {
      production_capacity: "100 kg fresh fodder per day",
      growth_cycle: "7 days",
      suitable_for: "Cattle, sheep, goats, horses",
    },
  },
  {
    id: "AGR035",
    name: "Portable Soil Salinity Meter",
    description:
      "Handheld device for measuring soil salinity levels in fields and greenhouses.",
    category: "Soil Management",
    tags: ["soil-testing", "salinity-management", "crop-health"],
    price: 1800,
    unit: "per meter",
    stock: 80,
    images: ["products/salinity-meter-1.jpg", "products/salinity-meter-2.jpg"],
    details: {
      measurement_range: "0-20 mS/cm",
      accuracy: "±2%",
      includes: "Carrying case and calibration solutions",
    },
  },
  {
    id: "AGR036",
    name: "Biological Pest Control Package",
    description:
      "Assortment of beneficial insects and organisms for natural pest control in crops.",
    category: "Pest Control",
    tags: [
      "biological-control",
      "integrated-pest-management",
      "organic-farming",
    ],
    price: 2500,
    discountPrice: 2250,
    discountPercentage: 10,
    unit: "per package (treats 1 hectare)",
    stock: 100,
    images: [
      "products/biological-control-1.jpg",
      "products/biological-control-2.jpg",
    ],
    details: {
      includes: "Predatory mites, parasitic wasps, nematodes",
      target_pests: "Aphids, thrips, whiteflies, soil pests",
      application_method: "Release according to instructions",
    },
  },
  {
    id: "AGR037",
    name: "Portable Grain Moisture Meter",
    description:
      "Digital grain moisture tester for quick and accurate moisture content measurement.",
    category: "Post-Harvest Technology",
    tags: ["grain-moisture", "harvest-management", "quality-control"],
    price: 1200,
    unit: "per meter",
    stock: 150,
    images: ["products/moisture-meter-1.jpg", "products/moisture-meter-2.jpg"],
    details: {
      measurement_range: "5-40% moisture content",
      grain_types: "Wheat, corn, rice, barley, soybeans",
      accuracy: "±0.5%",
    },
  },
  {
    id: "AGR038",
    name: "Drip Irrigation Starter Kit",
    description:
      "Complete drip irrigation system for water-efficient crop watering.",
    category: "Irrigation",
    tags: ["drip-irrigation", "water-efficiency", "crop-watering"],
    price: 3500,
    discountPrice: 3150,
    discountPercentage: 10,
    unit: "per kit (covers 0.5 hectare)",
    stock: 100,
    images: [
      "products/drip-irrigation-1.jpg",
      "products/drip-irrigation-2.jpg",
    ],
    details: {
      includes: "Pipes, drippers, filters, pressure regulators",
      water_saving: "Up to 70% compared to flood irrigation",
      suitable_for: "Vegetables, fruits, row crops",
    },
  },
  {
    id: "AGR039",
    name: "Poultry Incubator",
    description:
      "Automatic egg incubator with humidity and temperature control for hatching poultry eggs.",
    category: "Poultry Farming",
    tags: ["egg-incubator", "poultry-hatching", "farm-diversification"],
    price: 2800,
    unit: "per incubator",
    stock: 50,
    images: [
      "products/poultry-incubator-1.jpg",
      "products/poultry-incubator-2.jpg",
    ],
    details: {
      capacity: "500 eggs",
      temperature_range: "35-40°C",
      humidity_control: "Yes, with digital display",
    },
  },
  {
    id: "AGR040",
    name: "Farm Accounting Software",
    description:
      "Specialized accounting software for farm financial management and tax preparation.",
    category: "Technology",
    tags: ["farm-accounting", "financial-management", "tax-preparation"],
    price: 1500,
    unit: "per year subscription",
    stock: 200,
    images: [
      "products/farm-accounting-1.jpg",
      "products/farm-accounting-2.jpg",
    ],
    details: {
      features: "Income tracking, expense categorization, tax reports",
      compatibility: "Windows, Mac, mobile apps",
      support: "Online training and customer support included",
    },
  },
  {
    id: "AGR041",
    name: "Portable Electric Fence Energizer",
    description:
      "Battery-powered electric fence energizer for temporary fencing and rotational grazing.",
    category: "Livestock Management",
    tags: ["electric-fence", "rotational-grazing", "portable-fencing"],
    price: 450,
    unit: "per energizer",
    stock: 120,
    images: [
      "products/fence-energizer-1.jpg",
      "products/fence-energizer-2.jpg",
    ],
    details: {
      power_output: "0.5 joules",
      fence_length: "Up to 5 km",
      battery_life: "2-3 weeks on single charge",
    },
  },
  {
    id: "AGR042",
    name: "Silage Wrap",
    description:
      "High-quality plastic wrap for creating and preserving silage bales.",
    category: "Forage Management",
    tags: ["silage", "forage-preservation", "livestock-feed"],
    price: 1200,
    unit: "per roll (1500m x 750mm)",
    stock: 500,
    images: ["products/silage-wrap-1.jpg", "products/silage-wrap-2.jpg"],
    details: {
      material: "UV-resistant polyethylene",
      color: "White (reflects sunlight)",
      layers_recommended: "4-6 layers for optimal preservation",
    },
  },
  {
    id: "AGR043",
    name: "Vertical Farming LED Grow Lights",
    description:
      "Specialized LED lights optimized for vertical farming and indoor plant growth.",
    category: "Urban Farming",
    tags: ["led-lights", "vertical-farming", "indoor-growing"],
    price: 2500,
    discountPrice: 2250,
    discountPercentage: 10,
    unit: "per set (covers 10 square meters)",
    stock: 75,
    images: ["products/grow-lights-1.jpg", "products/grow-lights-2.jpg"],
    details: {
      spectrum: "Full spectrum with adjustable ratios",
      power_consumption: "250W",
      lifespan: "50,000 hours",
    },
  },
  {
    id: "AGR044",
    name: "Portable Livestock Water Trough",
    description:
      "Durable, portable water trough for livestock in pastures or remote locations.",
    category: "Livestock Management",
    tags: ["livestock-watering", "portable-equipment", "grazing-management"],
    price: 800,
    unit: "per trough",
    stock: 100,
    images: ["products/water-trough-1.jpg", "products/water-trough-2.jpg"],
    details: {
      capacity: "500 liters",
      material: "UV-resistant polyethylene",
      features: "Float valve for automatic refilling",
    },
  },
  {
    id: "AGR045",
    name: "Crop Harvesting Robots",
    description:
      "Autonomous robots designed for selective harvesting of fruits and vegetables.",
    category: "Machinery",
    tags: ["harvesting-robot", "automation", "labor-saving"],
    price: 75000,
    unit: "per robot",
    stock: 10,
    images: ["products/harvest-robot-1.jpg", "products/harvest-robot-2.jpg"],
    details: {
      harvesting_rate: "Up to 8 acres per day",
      crop_compatibility: "Strawberries, tomatoes, peppers",
      features: "AI-powered selection, gentle picking mechanism",
    },
  },
  {
    id: "AGR046",
    name: "Farm-to-Table Software Platform",
    description:
      "Software platform connecting farmers directly with restaurants and consumers.",
    category: "Technology",
    tags: ["farm-to-table", "direct-marketing", "supply-chain"],
    price: 2000,
    unit: "per year subscription",
    stock: 150,
    images: ["products/farm-to-table-1.jpg", "products/farm-to-table-2.jpg"],
    details: {
      features: "Inventory management, order processing, delivery scheduling",
      platforms: "Web and mobile apps",
      integration: "Payment processing and accounting software",
    },
  },
  {
    id: "AGR047",
    name: "Solar-Powered Produce Cooler",
    description:
      "Mobile, solar-powered cooling unit for on-farm produce storage and transportation.",
    category: "Post-Harvest Technology",
    tags: ["solar-cooling", "produce-storage", "off-grid"],
    price: 12000,
    unit: "per unit",
    stock: 20,
    images: ["products/solar-cooler-1.jpg", "products/solar-cooler-2.jpg"],
    details: {
      capacity: "1000 liters",
      temperature_range: "2-10°C",
      solar_panel: "600W with battery backup",
    },
  },
  {
    id: "AGR048",
    name: "Soil Fumigation Service",
    description:
      "Professional soil fumigation service for controlling soil-borne pests and diseases.",
    category: "Pest Control",
    tags: ["soil-fumigation", "pest-management", "crop-protection"],
    price: 5000,
    unit: "per hectare",
    stock: 50,
    images: [
      "products/soil-fumigation-1.jpg",
      "products/soil-fumigation-2.jpg",
    ],
    details: {
      treatment_method: "Injection and tarping",
      active_ingredients: "Eco-friendly fumigants",
      safety_period: "2-3 weeks before planting",
    },
  },
  {
    id: "AGR049",
    name: "Livestock Guardian Dog",
    description:
      "Trained livestock guardian dog for protecting sheep, goats, and other farm animals from predators.",
    category: "Livestock Management",
    tags: ["predator-control", "livestock-protection", "farm-dog"],
    price: 3500,
    unit: "per dog",
    stock: 15,
    images: ["products/guardian-dog-1.jpg", "products/guardian-dog-2.jpg"],
    details: {
      breed: "Great Pyrenees or Maremma",
      age: "1-2 years old",
      training: "Basic obedience and livestock bonding",
    },
  },
  {
    id: "AGR050",
    name: "Agricultural Waste Recycling System",
    description:
      "Integrated system for processing and recycling various types of agricultural waste.",
    category: "Waste Management",
    tags: ["waste-recycling", "sustainability", "circular-economy"],
    price: 45000,
    discountPrice: 40500,
    discountPercentage: 10,
    unit: "per system",
    stock: 5,
    images: [
      "products/waste-recycling-1.jpg",
      "products/waste-recycling-2.jpg",
    ],
    details: {
      capacity: "5 tons per day",
      output_products: "Compost, biogas, animal bedding",
      waste_types: "Crop residues, manure, processing waste",
    },
  },
];
